### ISSUE TITLE
Data failed validation check for duplicate rows

### ISSUE THREAD

**Issue by Shan-non** [UBC-MDS/maternal_health_classification#39]
According to validation checks our data has duplicate rows present. 

I am thinking we can:
- drop those rows (or half of them, so we do not have a duplicates), this makes sense if we think this was due to messy data entry, and if there isn't too many duplicates.
- OR keep them in the dataset since there aren't too many columns and even though some are float types none of the data (except blood sugar) has a decimal value, so with only 6 columns and a smaller window of "normal" values it seems possible that some are due to random chance.

We should inspect the data more closely to see how many duplicates are present and whether they seem likely due to chance, or disorganized data entry/collection.

**Comment by JiaQuanLim** [comment]
I did a quick check on excel, the entire dataset has 866 records of duplicated rows, based on my observation, i would say yes they are duplicated, but I am pretty confident they are different individuals who have the same records

Ive created a original id and check duplicate columns to check what are the duplicated rows. Here’s what I did:
1. Filter for those duplicated rows - check duplicate column with red cells.
2. Sort by the check duplicate column follow by original id to see if those exact duplicates are sequential or not, turns out they are not

You may download the csv and take a look, in my opinion, I think they are different individuals bcs if we were to assign an id to each row, we can see the duplicated rows are actually far from each other like 671,850 instead of being duplicated sequentially like 1,2,3,,, and so on.

Let me know if that make any sense and if it might justify why we dont drop the duplicated rows

[check_dup.csv](https://github.com/user-attachments/files/17964422/check_dup.csv)

**Comment by Shan-non** [comment]
Sounds good! Some written comments on this topic was added to our analysis file
